### ISSUE TITLE
Epub font style, text, line, paragraph display

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#109]
### Issue
Epub font style, text, line, paragraph display when custom option is not selected in yomikiru and EPUBReader.

- I compared the [EPUBReader](https://addons.mozilla.org/en-US/firefox/addon/epubreader/) and your app display of the text.
- In EPUBReader, when As defined in the book option is selected, it displays the text, as defined in the book.
- In Yomikiru, I think some spacing are not displayed as defined in the book.

- At the end, above and below the TL Note, there is a double line, it is not displayed in yomikiru.
- I also did not select custom font, so shouldn't the font be displayed as per the epub file's specified rule?
- I also did not select spacing for line, paragraph, they should also be displayed as per the epub file's rule.

**Comment by mienaiyami** [comment]
> Yomikiru, I think some spacing are not displayed as defined in the book.

There is no font defined in the book for this epub, So app is using default font from app.
Same goes for all other settings, but they are as defined in the book.

> I also did not select spacing for line, paragraph, they should also be displayed as per the epub file's rule.

In the above page there is no specified rule for line height and paragraph spacing in the epub file.

> At the end, above and below the TL Note, there is a double line, it is not displayed in yomikiru.

That is because of no specified width for line. I will make 100% as default with some vertical margin .


Close the issue if everything cleared.

**Comment by mienaiyami** [comment]
> If the buttons are not checked / ticked, then the settings (font family, line, paragraph spacing) are as defined in the opened EPUB file / chapter?

Yes, I found it redundant to write "custom" in front of every option.

**Comment by mienaiyami** [comment]
Can i get source of epub you gave so i can test on multiple files when have to?
