### ISSUE TITLE
epub continue reading

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#134]
### Description of the new feature / enhancement

The way the manga has a page number in continue reading, the same for epub to have progress indicator.

1. For example, I closed a manga chapter at page 5/30.
- When I open it again using the continue reading tab, the app will start the chapter at page 5.
2. Now,
- When I close an epub file at 30% and access it again using continue reading, it shows 30% on the page indicator, but it always starts at the top of the screen.
- So, I request for it to work the same way as for manga.
- So, when I close an epub file at x%, it should start from x% and not from the top.

### Scenario when this would be used?

While opening epub's from continue reading tab.

**Comment by mienaiyami** [comment]
I was planning to add this but its not same as using page number. You can check yourself, when you change size or font-size, progress changes even though same content is on view. 
Im planning to use same system as bookmark, which is against the logic of app.

I recommend you use bookmark feature till then as it records content on top of screen instead of progress.

**Comment by mienaiyami** [comment]
In case of Manga Reader, page number is stored on highest level and is updated every time page changes, so on closing reader/window, app is able to get this page number and update history.

But in epub reader, to autoscroll to exact line/paragraph I need to store its special ID(its css querySelector) and since it is not as bigger than simple page number its not possible to update it on each scroll. After reader closes, I cant check which line was on top of reader, so this is hard to add.
In bookmarks, reader stay open when adding bookmark so it works there.

Its solution might be not that hard but I havent had much time to work on it.

**Comment by Ultima14** [comment]
I've the same problem. It doesn't always work when I exit the epub.

**Comment by mienaiyami** [comment]
Please report if this is still an issue after v2.15.0.

**Comment by Ultima14** [comment]
Not working for me, it starts at the top of the chapter instead of the percentage

**Comment by mienaiyami** [comment]
@Ultima14  Will be helpful if you can record and show, or provide that epub to test. Are you on latest version, v2.15.4?
