### ISSUE TITLE
Smoother scrolling in book reader

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#143]
### Description of the new feature / enhancement

A bit more smoother scrolling than now in yomikiru while reading manga / webtoons.

### Scenario when this would be used?

While reading comics.

### Supporting information

Realm scans - [Top Tier Providence](https://realmscans.com/m050523/top-tier-providence-chapter-108/)

1. Open the above link.
2. Extract and open the same in yomikiru. - [Chapter 108.zip.](https://github.com/mienaiyami/yomikiru/files/11484564/Chapter.108.zip)
3. Scroll up and down (slowly or normally).
4. I feel the scrolling could be a bit more smoother in yomikiru after comparing with the website counterpart.
5. Please make the scrolling smoother to match with the website counterpart or more.
6. There is no error in dev tools, I checked it.

**Comment by mienaiyami** [comment]
Isnt it same as #140. 
I will look into it when i have time.

**Comment by mienaiyami** [comment]
To me its more laggy on website than in yomikiru. Please provide more info.

**Comment by mienaiyami** [comment]
If the issue is with the scrolling you do with mouse and not the keyboard then I'm afraid I can't do much there.
Though I had thought of better way to scroll with keyboard but don't have time to implement.
If there is issue with mouse scrolling then its probably because of page number or progress updating or just system limitations.

 As for #140, i can see it as well but cant say same for the manga reader.
