### ISSUE TITLE
CLI Parameters?

### ISSUE THREAD

**Issue by Zombeaver** [mienaiyami/yomikiru#146]
### Question

Are there any CLI arguments/parameters that can be used? Namely, can you specify zen mode via CLI? I'd really like to have files open to zen mode by default.

As a secondary question, would it be possible to allow the scroll wheel to change pages in the left to right reading mode?

**Comment by mienaiyami** [comment]
>  I'd really like to have files open to zen mode by default.

I can add it in setting itself to make reader open in zen mode by default, but I dont see how it can be useful as cli arg.

> would it be possible to allow the scroll wheel to change pages in the left to right reading mode?

I had thought about it before too but the issue comes when image is bigger than screen height and itself need scrolling.
It might be possible only when image is smaller or same as screen height.


Please create [enhancement issue](https://github.com/mienaiyami/yomikiru/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml) for better tracking.

**Comment by Zombeaver** [comment]
> I can add it in setting itself to make reader open in zen mode by default, but I dont see how it can be useful as cli arg.

For my use purposes I open everything via CLI so I would use it. That said, a setting in the UI would work as well.

> Please create [enhancement issue](https://github.com/mienaiyami/yomikiru/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml) for better tracking.

Done.

**Comment by mienaiyami** [comment]
Currently CLI of the app is not good. I had not given any effort in it other than being able to just open file explorer option.
When I'll have enough time, I'll try to improve it.
