### ISSUE TITLE
Bugs In v2.3.4

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#15]
### BUGS IN THEME MAKER

**1. --btn-color2**
It does not select all the secondary buttons and only selects some secondary buttons.

**2. --input-bg**
It changes the background color of buttons too.

**3. --topBar-hover-color**
It does not work and changes the color of top bar icons.

**4. --listItem-bg-color**
The pinned list color is linked to '--body-bg'. So '--listitem-bg-color' is unnecessary. It does nothing.

### BUGS IN READER

**2. Page Indicator**
- It freezes when the side list is pinned. This issue is also present in v2.3.3.
- It freezes when a value greater than the total number of pages of the concerned folder is entered.

**3. Memory Usage**

Compared memory usage of v2.3.4 and v2.3.3 side by side.
- Memory usage is high compared to the previous version.
- Takes 30 - 40 MB more memory than previous version in the reader.
- Memory usage goes down slowly in idle state compared to the previous version.
- But it uses 4MB to 6MB less than the previous version, when only the home screen is opened.

**Comment by mienaiyami** [comment]
>--btn-color2

It's actually hover color of buttons.
> --input-bg

It's there to make thing more homogenous but I plan to improve color system in future. Sorry for the inconvenience
> --topBar-hover-color

It's onMouseOver color of topbar buttons, i plan to add topbar button color itself soon.
>--listItem-bg-color

I will look into it, thanks for reporting.
___

> When a new shortcut key is assigned, it does not work until the reader is reloaded.

I am aware of that, due to some limitations I was unable to make shortcuts register instantly, but I will try my best to make it work.

> Memory Usage

I checked it and found out its similar to previous version. I have done nothing that might have resulted in increased memory usage. Please check again and report.

**Comment by mienaiyami** [comment]
Thanks for the data. It might be because I implemented a logger, which will log changes, warnings, errors, etc. for debug and user supports reasons. Also, since I'm very new to this framework, I don't know everything well. I have been searching to make it not stutter but no results so far. I will try my best to fix this in my free time after college.

**Comment by mienaiyami** [comment]
> Since it takes more memory than the previous version, I think it is better to revert the changes.

I have only made it possible to add new theme properties/ shortcuts without resetting all. So, I don't think it might be good idea to revert changes. And i have tested with old version as well, but I found only difference of 5-10mb, And its probably the logger i implemented, it is very useful for developer as well as user as you can find what caused error or what changed in log files

**Comment by mienaiyami** [comment]
I removed logger but there's only difference of 2mb ram, so I dont think logger is making any problem.

**Comment by mienaiyami** [comment]
> Do you mean that there is no logging in the next update unlike in v2.3.4?

There will be, since I have tested it thoroughly and it doesn't cause any ram issue.

Do note that because how this framework works RAM is not always same on app start. As I have also mentioned I experience no difference in RAM usage

**Comment by mienaiyami** [comment]
>2. Page Indicator
It freezes when the side list is pinned. This issue is also present in v2.3.3.

It doesn't freeze unless a higher number is entered, I will fix the later issue

**Comment by mienaiyami** [comment]
> --listItem-bg-color

It is actually being used, but its opacity is set to 0, which was not displaying because of a issue, I have fixed this.\

>Page Indicator

Issue fixed.

## Note: 
Please make separate issues for different issues/bugs so i can close one at a time
Close this issue if you have nothing to comment.
