### ISSUE TITLE
Collapsible / un-collapsible TOC side list in epub

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#190]
### Collapsible Table of Contents in epub side list.
- [TOC Types in epub.zip](https://github.com/mienaiyami/yomikiru/files/11859811/TOC.Types.in.epub.zip)

---

https://github.com/mienaiyami/yomikiru/assets/127277950/41d1d35f-11a8-45af-93bf-45a85202442d

### Scenario when this would be used?

Mainly in epub side list.

### Supporting information

https://github.com/mienaiyami/yomikiru/assets/127277950/01aa1f54-96d2-4405-9d7a-f7ba502d236b

**Comment by mienaiyami** [comment]
> * TOC Types in epub.zip

Thanks for that, saves me so much time.

Also, as in the video above if I were to add history for chapter read, it might not be good for performance of app. So i will only try for collapsible titles.

**Comment by mienaiyami** [comment]
> Sorry, but I did not understand.

The "✔️"  before titles. Im assuming they are indicator of visited.

**Comment by mienaiyami** [comment]
> Please release a version without anilist feature completely, neither in front end nor in the code of the app.

I don't get why there is a need for that. it is always off, and app does connect to internet unless you enter your token which you get from anilist's website. 
And even if you do you this feature, nothing is stored or sent other than just anilist progress, status, etc data.

It is still the same app with totally no difference if you never login.

If you have any questions or query as new issue because I think more people might want it, just ask.

**Comment by mienaiyami** [comment]
Or just take it to https://github.com/mienaiyami/yomikiru/discussions/168

**Comment by mienaiyami** [comment]
> Please release a version without anilist feature completely, neither in front end nor in the code of the app.

Can I know the reason for that? I might be able to clear some doubts.

**Comment by mienaiyami** [comment]
You don't need to, by default yomikiru only use internet to check for update and that's it, and even that can be disabled in settings.
