### ISSUE TITLE
add this feature  to make better 

### ISSUE THREAD

**Issue by wolfkingal2000** [mienaiyami/yomikiru#193]
### Description of the new feature / enhancement

Add use more ram to faster extracting or add settings to custom ram 
2. add multi loader or multiprocessing  and add multi drag and drop 
3 add tab like chrome  for multiplayer reading 
 went I add software default   using to open file every open file  open new windows please fix this 
add settings disabled open other file in  location file opened
add open Subfolders and their content 
thank you.

**Comment by mienaiyami** [comment]
> Add use more ram to faster extracting or add settings to custom ram

As @omodia said, extraction is not throttled by RAM, if there is need for RAM it will use everything available or what's set by OS (powershell is used to extract on windows version). 

> 2. add multi loader or multiprocessing and add multi drag and drop
3 add tab like chrome for multiplayer reading 

If you want to open more than one at a time you can click `ctrl + n` for a new window. Each window has its own thread. Since it is javascript based app, it cant really do multiprocessing but extracting and pdf are handled by external services which I really make.


> add multi drag and drop

Can you explain this more?
If you mean opening more than one file at once, then that might be possible soon. Im working on option to allow dynamic loading (for folder and pdf type only).

Will be closing this issue since none of them are practical.
