### ISSUE TITLE
Library and library thumnail?

### ISSUE THREAD

**Issue by ALiveFromDead** [mienaiyami/yomikiru#206]
### Description of the new feature / enhancement

Can someone tell me how to create library and add thumnail to it?
Thanks!

**Comment by mienaiyami** [comment]
This app is designed to use your file whole storage as library (kind of). You can open manga from anywhere. You must select a "default location" from settings, it will be the location that will be loaded first when launching app, generally it should be where all of your manga/manhwa titles are. 
Thumbnails are not supported because whole storage act as library and images for thumbnail itself is not present in most downloads.

I would recommend reading "Usage & feature" in settings for more info.
