### ISSUE TITLE
Add multi  extractor  and one bug went fix about PDF

### ISSUE THREAD

**Issue by wolfkingal2000** [mienaiyami/yomikiru#216]
Add multi  extractor mean that we can put several files together so that he can extract them and send them to Temp folder so that he can cough in time. Like Windows explorer, select them with CTRL and right click and option extract in background 

And one bug I use PDF like this get bad and blur  view because first page is very large, other page smaller that like this  PDF 
[ch 41(3).pdf](https://github.com/mienaiyami/yomikiru/files/12181502/ch.41.3.pdf)

**Comment by mienaiyami** [comment]
> Add multi extractor mean that we can put several files together so that he can extract them and send them to Temp folder so that he can cough in time. Like Windows explorer, select them with CTRL and right click and option extract in background

Firstly, I just recommend getting direct images instead of pdf and such, but if that is not possible, there are multiple tools you can find that convert pdf to images. I will try to make one builtin this app when I have enough time.



> And one bug I use PDF like this get bad and blur view because first page is very large, other page smaller that like this PDF
> [ch 41(3).pdf](https://github.com/mienaiyami/yomikiru/files/12181502/ch.41.3.pdf)

Are you using a low "PDF scale" value, render quality is totally dependent on that not the first page. You can try 64-bit version of app for a bit faster render, but it will have more RAM usage.

**Comment by mienaiyami** [comment]
Can access from settings now .
