### ISSUE TITLE
Some Text color secondary (epub, pdf, zip) are linked to text color

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#227]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Change the secondary text color to another color.
2. Some button styled epub, zip, pdf that are in location tab, settings menu are not linked to text color secondary, but are linked to font color.

---

https://github.com/mienaiyami/yomikiru/assets/127277950/d2496e83-f918-43ba-ab6e-9381ba531065

### ✔️ Expected Behavior

For the epub, zip, pdf that are in location tab, settings tab, to be linked to text color secondary.

### ❌ Actual Behavior

They are linked to text color.

**Comment by mienaiyami** [comment]
I did that in https://github.com/mienaiyami/yomikiru/issues/217#issuecomment-1655649420 because size wasnt the problem. 
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/fb7912c3-557a-4c5a-8ef8-0877688f5933)
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/4a477ad4-5dea-467e-b5cc-27622939ac2f)

As you can see that they are hard to read, even with same size. 
If you have any suggestion, then do mention. Otherwise, I think I might revert the changes because its just a "bad theme" thing (even thought I made that theme).

**Comment by mienaiyami** [comment]
What I meant to say is, I intentionally made it to use font color in settings because they aren't really small, https://github.com/mienaiyami/yomikiru/issues/217#issuecomment-1655649420, they just have a bad match up of color in case of "theme2" and "secondary text color". The contrast ratio is bad and I couldn't think of a better way to fix this. 

Before https://github.com/mienaiyami/yomikiru/issues/217#issuecomment-1655649420, and even now (outside settings) they use came color as text beside them. 
Because they are used in places where both "font color" and "secondary font color" are, I decided not to give it its own variable for color because it can make it stand out a lot in some place.
