### ISSUE TITLE
Some font names in epub have double quotation marks

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#239]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Open any epub.
2. Choose custom font family.
3. Some font names displayed have double quotation marks.
4. And I found one that has wrong name. (Nunito)
- At the start of the video you can see the font name as Nunito, below it is "Nunito Sans Normal".
- But in the font settings page of windows, it is Nunito, Nunito Sans.

---

### ✔️ Expected Behavior

For font names to not have double quotation marks.

- If you open the control panel and go to the font page, either the old one or the new one, no font names have double quotation marks.
- The new control panel / font setting page shows the font names properly.
- While many of the font names in the old control panel have regular appended to them.
- So I think the new font page is better.

### ❌ Actual Behavior

Some fonts have double quotation marks, while I found one that has wrong name.

**Comment by mienaiyami** [comment]
> 4\. And I found one that has wrong name. (Nunito)
> 
> * At the start of the video you can see the font name as Nunito, below it is "Nunito Sans Normal".

It's because they are font faces. There are many things to say on this, but I don't think I will be able to explain well enough. 
If I were to just get font names, it would be a total mess, performance wise as well.
Here you can see that I'm getting all fonts as individual, and it gives me full control, but not the performance.
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/5f193b7e-d6e0-4dd1-9d14-40ea64975828)
Still, even after this, I was planning to use this, but it didn't work right. Some font family names were just not working on selecting, after all that I just decided use a system-based library to get fonts.

As for the double quotation, since some fonts have space between them, they need to be wrapped in quotation so it can be used as app's font. Though I can write more code to remove it, I thought it was just unnecessary.
