### ISSUE TITLE
Skipped Chapter Warning

### ISSUE THREAD

**Issue by kajitdahli** [mienaiyami/yomikiru#243]
### Description of the new feature / enhancement

Sometimes when downloading a series a chapter may be missed due to an error, if it's possible it would be great to add a feature that detects when you go to the next chapter, if it's a skipped chapter.

Regarding the logic I guess it can improve over time when people report problems in certain naming sequences etc...

### Scenario when this would be used?

When someone is reading a manga that has numbered chapters.
In other cases one should be able to disable this warning in the settings / or in the side panel in the reader.

### Supporting information

I think it would look good if the warning is added to the transition screen at the end

**Comment by mienaiyami** [comment]
Unfortunately, it's very impractical.
As @omodia said.
> * I don't think it's possible / easy to add this, because yomikiru is not the one downloading the chapters.

I attempted this a while ago, but since yomikiru doesn't handle downloads, I have limited control over chapters because they can be named anything, for example, `Vol.2 ch.30`, `30. Chapter Title`, etc. 
It also creates the issue of bad sorting order, but nothing can be done about it. 


Although there is no "warning", you can still see which chapter will be opened next using the "Chapter Transition Screen" option.
- In Vertical scroll mode 
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/7e915aa7-e709-4aaf-be4e-715c0f59d37b)

- In LTR  or RTL mode 
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/170df60b-a384-46a5-a78d-e04dbc37c9c3)

**Comment by mienaiyami** [comment]
Feel free to ask if you have more questions or feature requests.
