### ISSUE TITLE
Disable reader side list option (Not hide, but do not execute)

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#269]
### Description of the new feature / enhancement

I request for the option to disable the reader sidelist for the entire app (Not hide, but do not execute). It might need app restart.

The reader side list is an amazing feature you thought for the app, but when there are many chapters for a comic or txt, single xhtml files, I found when enter / exit full screen it seems slow there, which is normal as there are 1000's of chapters.
Let's take martial peak as example, its comic version has 3500+ chapters, novel version is 4900+ chapters and both still ongoing. I think disabling (not executing) the side list via an option would help the app further improve both performance and memory usage.

This feature is a way to future-proof the app. This is my humble request.

### Scenario when this would be used?

When a comic or novel has many chapters. If needed then user disable side list, if no need then user no need to disable side list.

### Supporting information

I like that you had implemented single txt and xhtml files to be readbale for novels. A great feature no other app has implemented. I read martial peak novel both as epub and single xhtml files. The single xhtml files had improved performance of the app by a far greater margin than reading them as epub.

Sorry for the long words and bad english.

**Comment by mienaiyami** [comment]
>but do not execute

Its not possible for epub, without it you wouldnt be able to change chapters or use internal link.
Im aware of the bad performance when changing chapters in epub reader as I too read a lot. I haven't been able to give it much time to improve it. It will require a lot of free time and clear mind to think for better and more performant solutions.

Also, while I recommend just moving read chapters in other folder if they are over 1000, I should have provided an option to not check for "valid folder" (with at least one image). Because now on initial reader open, it read all folders which might be resulting in lag for large chapter count. #272

**Comment by mienaiyami** [comment]
If you want a temporary solution you can use this in custom css file

```css
.readerSideList:not(#dummy#dummy){
  display:none;
}
```

**Comment by mienaiyami** [comment]
I assumed it was also for manga reader. But that will continue at #272 I guess.
