### ISSUE TITLE
Implementing Real-ESRGAN for Image Quality Improvement

### ISSUE THREAD

**Issue by MattyMroz** [mienaiyami/yomikiru#289]
### Type of reader (if reader related)

image

### Description of the new feature / enhancement

The program can further impress users by adding a feature that uses Real-ESRGAN to improve image quality. This feature would create a new folder with rescaled images. Although the process may be a bit slower, the results are impressive. Real-ESRGAN is a powerful tool for improving image quality. There is also Real-CUGAN available here, which can provide similar features.

Links:
Real-ESRGAN:
https://github.com/xinntao/Real-ESRGAN
https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan

Real-CUGAN:
https://github.com/nihui/realcugan-ncnn-vulkan

Real-ESRGAN-GUI:
https://github.com/tsukumijima/Real-ESRGAN-GUI

**Comment by mienaiyami** [comment]
Unfortunately what @omodia said is true.
These days I'm not even getting time to fix the existing issue let alone implement something this big. Plus, it will require python packages, I don't have much experience in that either and app's size will be too big with those included.

However, there's #245 which is similar to this and will improve quality. And in my opinion, it will be better to use existing GUI instead because in the end I will need to save those upscaled images on drive to display them either way.
