### ISSUE TITLE
Adding Metadata

### ISSUE THREAD

**Issue by Nu70ry** [mienaiyami/yomikiru#291]
### Type of reader (if reader related)

None

### Description of the new feature / enhancement

A good addition to this program would be the ability to manual filling/searching metadata.

something like:
genre/tags, original title, artist, publisher....
Maybe also the possibility to give a personal rating.

And thanks for this tool it's really good.

### Scenario when this would be used?

In a search query to more narrow down for metadata

**Comment by mienaiyami** [comment]
Most of the reason is same as https://github.com/mienaiyami/yomikiru/issues/292#issuecomment-1740667017, but this specifically adds too much unnecessary complexity in the app. As this app is not a host/downloader, i dont think there is any need for such options. 
Main focus of this app was to provide better reading experience and not a library manager as @omodia mentioned.
