### ISSUE TITLE
The scroll speed setting doesn't seem to be doing anything

### ISSUE THREAD

**Issue by Advonso** [mienaiyami/yomikiru#296]
### Type of installation

Setup (.exe)

### Type of reader (if reader related)

image

### Steps to reproduce

I adjusted the both Scroll A and B 1-500, alternating between the two and which had more or less. I also ran as Admin. Still, nothing seemed to change.

### ✔️ Expected Behavior

Faster scroll speed

### ❌ Actual Behavior

Nothing

**Comment by Advonso** [comment]
> Its working for me. The scroll speeds are for keys.
> 
> Scroll A = Scroll up / down using w/s (Customizable in shortcut keys) Scroll B = SpaceBar (Customizable in shortcut keys)

You're right that it does work for shortcuts/hotkeys, but I honestly think it should also work with the mouse scroll wheel.

**Comment by mienaiyami** [comment]
Sorry for the late reply, I had my end term exams.

> I honestly think it should also work with the mouse scroll wheel.

Please create a new feature request issue for that.



> The mouse scroll speed is handled by the OS, not the app.
> 
> Reference #144 comments.

I only meant as in "current" version. I felt no need for that personally, because you could just use the middle mouse button for any scrolling speed. 
Please check if it is sufficient before creating new feature request issue.
