### ISSUE TITLE
Reader Bugs

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#80]
### Setup or portable version of the app?

Portable

### Reader Bug
- Open any manga in the reader.

### ✔️ Expected Behavior

1. To show all pages.
2. And to be able to scroll up the images even when the side list is pinned.

### ❌ Actual Behavior

1. Only shows one page.
2. And Cannot scroll up the images when the side list is pinned.

https://user-images.githubusercontent.com/116664905/228539543-d17d8047-2ef9-499b-8da7-4f944e64761f.mp4

**Comment by mienaiyami** [comment]
I recommend that you do `ctrl`+`=` or `0` once as old app version had a related bug which caused system buttons to not scale with app. 

And regarding the main issue, I tried it on both setup and portable version and couldn't find any issue, please try restarting app after  `ctrl`+`=` or `0` or send me the test folder.

**Comment by mienaiyami** [comment]
Its working as expected without any bug.
![image](https://user-images.githubusercontent.com/84740082/228576881-75e20654-72c2-43f7-aa9f-1ea041c0f49d.png)

**Comment by mienaiyami** [comment]
Try `ctrl` + `0` and then restart app. Or there might be some missing information to the bug

**Comment by mienaiyami** [comment]
> The image counting is working as intended, but the total images is stopped at 1.

Please provide screenshots as I had not encountered such issue.

**Comment by mienaiyami** [comment]
> I recommend that you do `ctrl` + `=` or `0` once as old app version had a related bug which caused system buttons to not scale with app.

Hope it helps

**Comment by mienaiyami** [comment]
This application does not have a digital certificate because it costs a lot and I make zero money off this app, So your anti virus might be detecting it as malware.
You can try saving settings and deleting app and reinstalling, but i think window zoom is hiding your pagenumber as i can see system button and topbar are not lined in you screenshot
![image](https://user-images.githubusercontent.com/84740082/228597001-4cf89dc4-52be-44c9-9025-a2c6fe7312ec.png)

**Comment by mienaiyami** [comment]
If you dont mind, can you send recording if `ctrl` + `=` or `-` focused on system buttons.

**Comment by mienaiyami** [comment]
> I think I know the reason. You can also reproduce this malware behavior.


That will be helpful, please mention. 
Also do note that since this app is not signed, I have to use my custom update system because i couldn't get any ither to work, which work by deleting old files and extracting new app.zip in same folder.

> It never flagged the application as malware until now.

If you had ever used setup version of this app you would know, theres always a popup saying this app can be harmful then auto-updating.

**Comment by mienaiyami** [comment]
> It's hidden. Can briefly see the page number while scaling up.

Thanks for this, I have identified the issue and will fix soon

**Comment by mienaiyami** [comment]
> Steps to reproduce the malware behavior.

That is because every time app start it check theme file for changes and saves, when refreshed repeatedly saving process is interrupted and cause this error.

**Comment by mienaiyami** [comment]
I dont have any knowledge about how anti-viruses work so cant say anything.

**Comment by mienaiyami** [comment]
> Have you found a method to stop the increasing RAM usage when chapters are changed without any time interval?

Sorry but i havent had much time to test different things,

**Comment by mienaiyami** [comment]
Please check again in new version after doing `ctrl` + `0` when input box is not selected.
