### ISSUE TITLE
epub behavior

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#99]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open the below attached zip file and extract epub
2. Open the EPUB, Wait for it to load.
3. See the RAM usage.
4. After loading, click on custom font or any other option, it stops responding.
5. After sometime, the application closes the epub. After refreshing the application - 'Unable to parse settings file, making new.'

**Comment by mienaiyami** [comment]
Did you try with other epub?
This certain file is causing the issue here because it is compressed to half its size (epub size is 12mb but after extracting its 30) and on top of that all of this 30mb is text content files with 2000+ chapters.
An average volume has 400kb-1mb text content files. but i have tested app on combination of 5 volumes with over 400chapters and it is working normally. 

Only way possible to read this file is to load files dynamically then clear files once they are not on view, but considering the structure of this app it might be hard to implement any time soon

**Comment by mienaiyami** [comment]
> epub's chapter list be in the side list?

whole toc
